name: Initialise the app environment

inputs:
  node-version:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
      - uses: actions/checkout@v2
      - uses: Stephen-vellaichamy-selvaraj/Contentful-Jamstack@main
        with:
          feed_list: "https://whitep4nth3r.com/feed.xml"
          commit_message: "Updated README with latest blog posts"
      
