name: Gatsby Publish

on:
  workflow_call:
    secrets:
      GATSBY_BUILD:
        description: 'A token passed from the caller workflow'
        required: false
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Stephen-vellaichamy-selvaraj/Contentful-Jamstack@main
        with:
          access-token: x-access-token:${{ secrets.GITHUB_TOKEN }}
