jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
        - name: Read a variable
          run: echo "MY_GIT_APP_ID value is ${{ vars.GIT_APP_ID }}"    
          
        - uses: actions/checkout@v2
        
        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: '18.x'

        - name: Cache dependencies
        - uses: actions/checkout@v2
        - uses: kenchan0130/actions-system-info@master
          id: system-info
        - uses: actions/cache@v2
          with:
            path: ~/.npm
            key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-node-
                    
        - run: npm ci
        - run: npm run build

        - name: Deploy
          uses: Stephen-vellaichamy-selvaraj/Contentful-Jamstack@main
          with:
            deploy_key: ${{ secrets.GIT_API_KEY }}
            publish_dir: _site
