name: Eleventy Build on Contentful Publish Event
on:
	repository_dispatch:
    	types: [publish-event]

jobs:
  top-secret:
	runs-on: ubuntu-latest
 	env:
  	 MY_GIT_APP_ID: ${{ vars.GIT_APP_ID}}

    	steps:
     		- name: Read a variable
       		run echo "GIT_APP_ID value is " ${{ vars.GIT_APP_ID}}
    	
