name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Stephen-vellaichamy-selvaraj/Contentful-Jamstack@main
        with:
          access-token: ${{ secrets.GATSBY_BUILD }}
