name: Update GitHub Profile README
on:
  repository_dispatch:
    types: [contentful.deploy]
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: Stephen-vellaichamy-selvaraj/Contentful-Jamstack
        with:
          commit_message: "Updated README with latest blog posts"