name: Latest blog post workflow
on:
  repository_dispatch:
    types: [publish-event]
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update GitHub Profile README
      uses: Stephen-vellaichamy-selvaraj/Contentful-Jamstack@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        header: "Test Header! 👋"
        subhead: "Test SubHead"
        footer: "**Test Footer!**"
        ref: "main"
        excludeActivity: '["WatchEvent"]'
