name: Update GitHub Profile README
on:
  repository_dispatch:
    types: [publish-event]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update GitHub Profile README
      uses: Stephen-vellaichamy-selvaraj/Contentful-Jamstack@main
      with:
        header: "Hey, I'm Ryan! 👋"
        subhead: "Currently a student in Singapore, passionate about creating all-things-tech to improve society."
        footer: "**Learn more about me at [ryanthe.com](https://www.ryanthe.com)!**"
        ref: "main"
        excludeActivity: '["WatchEvent"]'
        excludeRepo: '["theboi/theboi"]'
