name: Contentful Publish

on:
  repository_dispatch:
    types: [publish-event]

jobs:
  build:
    runs-on: ubuntu-latest
    env: # Add environment variables here
      CONTENTFUL_SPACE_ID: '007inbhlnus1'
      CONTENTFUL_ACCESS_TOKEN:  '7wMQgKx3LGaqtmfhZei2xRPACLr2iQHpNs4dNkv_9B4'
      CONTENTFUL_ENVIRONMENT: 'master'
      CONTENTFUL_HOST:  'preview.contentful.com'    
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GIT_API_KEY }}
