name: Gatsby Publish

on:
  repository_dispatch:
    types: [publish-event]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_APP_ID: ${{ vars.GIT_APP_ID }}
      
    steps:
      - uses: actions/checkout@v3
      - uses: Stephen-vellaichamy-selvaraj/Contentful-Jamstack@main
        with:
          access-token: ${{ secrets.GIT_API_KEY }}
