name: Contentful Build on Push
on:
    repository_dispatch:
      types: [publish-event]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
         node-version: '18.x'
    
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
         path: ~/.npm
         key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
         restore-keys: |
            ${{ runner.os }}-node-
    
      - run: npm ci
      - run: npm run build
    
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GIT_API_KEY }}
          publish_dir: _site
