name: Secrets and Environment Variable
on:
 workflow_dispatch
jobs:
  top-secret:
	runs-on: ubuntu-latest
 	env:
  	 MY_GIT_APP_ID: ${{ vars.GIT_APP_ID}}
    	steps:
          - name: Read a variable
	  run echo "GIT_APP_ID value is " ${{ vars.GIT_APP_ID}}
    	
