name: Secrets and Environment Variables

on:
  repository_dispatch:
    types: [publish-event-test]

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env:
      MY_APP_ID: ${{ vars.GIT_APP_ID }}

    steps:
      - name: Read a variable
        run: echo "MY_GIT_APP_ID value is ${{ vars.GIT_APP_ID }}"

      - name: Tell me a secret!
        run: echo "My existing secret is ${{ secrets.GIT_API_KEY }}"
      
      - name: Unset secret
        run: echo "My unknown secret is ${{ secrets.DOES_NOT_EXIST }}"
      
      - name: Github stuff
        run: echo "My Github repo is called ${{ github.repository }}"
      
      - name: Read an env variable
        run: echo "My APP_ID value is ${{ env.GIT_APP_ID }} (also accessible as $MY_APP_ID)"
